/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { ScenarioType } from './scenarioType';

export type GetZoningGeojsonCitiesCityIdZoningGeojsonGetParams = {
/**
 * minLng,minLat,maxLng,maxLat — spatial filter
 */
bbox?: string | null;
/**
 * Filter by scenario label e.g. '2024', '2025-06'
 */
scenario?: string | null;
/**
 * Filter by scenario type: 'year' or 'month'
 */
scenario_type?: ScenarioType | null;
};
