/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { HazardHit } from './hazardHit';
import type { LocationContextPsaClassifications } from './locationContextPsaClassifications';
import type { NearbyEstablishment } from './nearbyEstablishment';
import type { ZoneHit } from './zoneHit';

export interface LocationContext {
  geometry_type: string;
  buffer_meters: number | null;
  zoning: ZoneHit[];
  hazards: HazardHit[];
  nearby_establishments: NearbyEstablishment[];
  psa_classifications: LocationContextPsaClassifications;
}
