/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { LocationContext } from './locationContext';

export interface LocationAnalyzeResponse {
  answer: string;
  city_name: string;
  context: LocationContext;
}
