/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { PsaEntry } from './psaEntry';

export type LocationContextPsaClassifications = {[key: string]: PsaEntry[]};
