/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */
import type { LocationAnalyzeRequestGeometry } from './locationAnalyzeRequestGeometry';

export interface LocationAnalyzeRequest {
  geometry: LocationAnalyzeRequestGeometry;
  question?: string | null;
  /**
     * @minimum 50
     * @maximum 5000
     */
  buffer_meters?: number;
}
