/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export interface PSOCResponse {
  /**
     * Unique integer ID of the major group
     * @minimum 1
     */
  id: number;
  /**
     * Major group code
     * @minimum 1
     */
  majorcode: number;
  /**
     * Title
     * @minLength 1
     */
  title: string;
  /**
     * Description
     * @minLength 1
     */
  description: string;
  /**
     * Version
     * @minimum 1
     */
  version: number;
}
