/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

export type ScenarioType = typeof ScenarioType[keyof typeof ScenarioType];


export const ScenarioType = {
  year: 'year',
  month: 'month',
} as const;
