/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * BizNest Geo-Intelligence API
 * OpenAPI spec version: 0.1.0
 */

/**
 * List/get response — geometry excluded (use pmtile_url for rendering).
 */
export interface ZoningAreaSummary {
  id: string;
  city_id: string;
  zone_type?: string | null;
  color_hex?: string | null;
  severity?: number | null;
  scenario?: string | null;
  scenario_type?: string | null;
  pmtile_url?: string | null;
  created_by: string;
  created_at: string;
}
